### ISSUE TITLE
Covidlist

### ISSUE THREAD

**Issue by db0sch** [opensourcerails-org/suggestions#1]
### Name of application

Covidlist

### GitHub

https://github.com/hostolab/covidliste

### Relevance

An app dedicated to find leftover vaccination slots, with secure data (encrypted at the DB level), which endured a high traffic load when the vaccination slots were a rare commodity in France. Integrated with multiple third party services for emails, geocoding, sms... And with a 2 side interface: patient, and vaccination center staff.

### Link to logo
!(logo)[https://pbs.twimg.com/profile_images/1394574659644010499/Fiv_tQRY_400x400.jpg]

**Comment by joshmn** [comment]
ah, bonjour! added :)

**Comment by db0sch** [comment]
Bonjour 👋 
Merci @joshmn 🙏
