### ISSUE TITLE
Suggestion: Loomio

### ISSUE THREAD

**Issue by robguthrie** [opensourcerails-org/suggestions#3]
### Name of application

Loomio

### GitHub

https://github.com/loomio/loomio

### Relevance

Loomio is a tool for organizations to have discussions and make collaborative decisions together. 
Ideal for boards, governance teams, community groups, self managing organizations, political parties and more. 

### Link to logo

SVG and PNG logos available here:  https://www.loomio.org/brand

![logo_sky_256h](https://user-images.githubusercontent.com/486367/131933134-517d82f3-3c0d-46f8-848b-97948a3a077a.png)

**Comment by joshmn** [comment]
already there! but not without this new logo. updated! thank you :)
