### ISSUE TITLE
Add Upcase!

### ISSUE THREAD

**Issue by gnfisher** [opensourcerails-org/suggestions#4]
### Name of application

Upcase

### GitHub

https://github.com/thoughtbot/upcase

### Relevance

A post-bootcamp Ruby on Rails finishing school open-sourced by [thoughtbot](https://thoughtbot.com)
![upcase-logo](https://user-images.githubusercontent.com/4742306/132062350-d90b7471-78bd-4da8-b999-78dbad3c2b77.png)

### Link to logo

Attached!

**Comment by joshmn** [comment]
I do not know how I missed this one! Posted, and thank you!
